# Generated by Django 5.2 on 2025-05-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quantity',
            new_name='amount',
        ),
    ]
