# Generated by Django 5.2 on 2025-06-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_rename_quantity_recipeingredient_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.SlugField(blank=True, max_length=32, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
