# Generated by Django 5.2 on 2025-05-24 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_remove_favorite_unique_favotite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Введите название тега.', max_length=32, unique=True, verbose_name='Название тега'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Введите уникальный идентификатор тега', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Разрешены только цифры и буквы', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Уникальный идентификатор'),
        ),
    ]
