version: '3.3'

volumes:
  pg_data:
  static:
  media:
  docs:

services:
  db:
    container_name: db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: alexplum17/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static/
      - media:/app/media/

  frontend:
    image: alexplum17/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: alexplum17/foodgram_nginx
    ports:
      - "8000:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - docs:/usr/share/nginx/html/api/docs/
      - media:/usr/share/nginx/html/media/
      - static:/usr/share/nginx/html/backend_static/
    depends_on:
      - backend
      - frontend
