# Generated by Django 4.2 on 2025-06-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_link',
            field=models.SlugField(max_length=32, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
