# Generated by Django 4.2 on 2025-06-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_recipe_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_link',
            field=models.SlugField(blank=True, max_length=32, null=True, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
